### ISSUE TITLE
Summarize documentation of existing coverage tool

### ISSUE THREAD

**Issue by markusnewtonh** [DD2480G19/teammates#33]
**Document the entire group's experience in using a "new"/different coverage tool in `README`.**
- How well was the tool documented? 
- Was it possible/easy/difficult to integrate it with your build environment?

Summarized when everyone has used the tool.

**Comment by markusnewtonh** [comment]
https://www.jacoco.org/jacoco/

This tool is already integrated with TEAMMATES, see _**Running the tests:**_

https://teammates.github.io/teammates/development.html


_"You can generate the coverage data with jacocoReport task after running tests, e.g.:_

`./gradlew componentTests jacocoReport`

_The report can be found in the build/reports/jacoco/jacocoReport/ directory."_

**Comment by markusnewtonh** [comment]
https://docs.gradle.org/current/userguide/jacoco_plugin.html

**Comment by markusnewtonh** [comment]
My experience:

The tool used was `Jacoco`, which is well-documented. The project had also already integrated Jacoco into the existing testing and had clearly documented steps of how to run Jacoco together with the tests. This made it extremely easy to use.

**Comment by FalkWasTaken** [comment]
I had the same experience. I specifically found the generated HTML report to be very clear and easily interpretable!
